---
title: "BITE"
---

the Biotic Disturbance Engine

BITE is a general model to simulate biotic disturbances in forest ecosystems. BITE is a modeling framework that is general enough to simulate a wide range of biotic disturbance agents, from fungi to large mammals. The framework is also simple and modular (in order to also be applicable in situations where knowledge about an agent is limited, as is the case with new invaders). BITE allows the quantification of the impacts of emerging pests and pathogens on forests in time and space.

BITE is coupled with iLand and its implementation makes heavy use of the Javascript Engine provided by Qt (and also used by iLand). The implementation of agents in BITE is purely done in Javascript (which accesses the BITE engine written in C++). A [BiteAgent](bite.qmd#biteagent)consists of several [BiteItems](bite.qmd#iditems); each item implements one aspect of the life cycle of an agent.



### Full [BITE documentation](https://iland-model.org/bite/index.html)




## Integration in iLand




### Project file


BITE is enabled and disabled in the [project file](project-file.qmd).

In section "modules" (similar to e.g. the fire module):

| **key** | **description** |
| --- | --- |
| enabled | boolean switch to enable (true) or disable (false) the module. |
| file | path to a Javascript file that contains the definition of agents. Note that further files can be included via the **include()** function of iLand. |


 



## Outputs


 


### Annual summary for each Bite agent


Table Name: bite
The output provides annual statistics for each simulated biotic agent.


| **caption** | **datatype** | **description** |
| --- | --- | --- |
| year | integer | simulation year |
| agent | string | name of the biotic agent |
| NColonized | integer | Number of cells that were (at the end of the year, without mortality) colonized by the agent |
| NDispersing | integer | Number of cells that were actively spreading the agent in this year |
| NNewlyColonized | integer | Number of cells that were newly colonized in this year |
| agentBiomass | double | total biomass of the agent (on all active cells, if applicable) |
| treesKilled | integer | number of host trees killed in the current year |
| volumeKilled | double | total volume (m3) of trees killed by the agent in the current year |
| totalImpact | double | total impact (e.g. for defoliatores foliage mass consumed) |
| saplingImpact | integer | number of sapling cohorts affected (browsing) |
| saplingKilled | integer | number of sapling cohorts killed |




### Bite cell level output


Table Name: user defined
Bite cell level output. This output is defined by the agents via Javascript (using a BiteOutput item).
See: <http://iland-model.org/bite/#/BiteOutput>

In addition to the user-defined columns, the output includes a number of fixed columns.

These are:


| **caption** | **datatype** | **description** |
| --- | --- | --- |
| year | integer | simulation year |
| idx | integer | cell index (cell Id) (see 'index' variable), useful for spatial analysis |
| hostTrees | integer | number of host trees (>4m, passing the 'hostFilter') in the current year |
| treesKilled | integer | number of host trees killed (>4m) in the current year |
| volumeKilled | double | total volume (m3) of trees killed (>4m) by the agent in the current year |
| totalImpact | double | total impact (e.g. for defoliatores foliage mass consumed) |
| hostSaplings | integer | number of sapling cohorts that are potential host in the current year (depending on the current filtering) |
| saplingImpact | integer | number of sapling cohorts affected (browsing) |
| saplingKilled | integer | number of sapling cohorts killed |


 
