---
title: "browsing"
---



# browsing by ungulate game species





## concept


Browsing on regeneration is a process that affects saplings up to a height of around 2m (depending on snow conditions of the spot). The destruction of buds causes a reduction in growth as well as mortality after repeated browsing on the same plant. In natural forest ecosystems (referring to forests themselves, but also to deer population), browsing usually has only minor impacts on the succession of ecosystems (see e.g. [Winter et al. 2015](http://link.springer.com/article/10.1007/s10342-015-0901-3#/page-1)), however, in forest ecosystems that are characterized by antropogenic influences browsing can strongly manipulate forest development (see e.g. [Pröll et al. 2015](http://link.springer.com/article/10.1007/s10342-014-0851-1)).
The submodule presented here uses an annual probability that the saplings up to a height of 2m on a pixel are affected by browsing. If a species on a pixel is affected by browsing, their sapling cohort does not grow during that year. If a species on a pixel is affected by browsing for several years consecutively, their sapling cohort dies from stress. The number of years required to kill saplings depends on the species specific years in which they tolerate stress (see [sapMaxStressYears](species-parameter.qmd)). To also account for processes that hamper regeneration during germination, we developed a module for [ground vegetation](ground-vegetation.qmd).



## implementation


As the overwhelming majority of forested land is not protected against browsing, and the species parameters on regeneration are usually derived from field measurements, we assumed that regeneration parameters are already influenced by a "natural" background browsing probability. To estimate the preference of ungulates for certain tree species, we defined a browsing probability parameter (with 0=0% and 1=100% browsed). This probability can be determined by inventory data or roughly estimated by experts and describes the annual probability that the saplings on a pixel of a species (up to a height of 2m) are affected by browsing. We used inventory data from www.wildeinflussmonitoring.at to regionally calibrate the species parameters in Austria.



### parameters in the project file


The browsing module is controlled by a section in the [#settings_2|*settings*-section](project-file.qmd) of the [project file](project-file.qmd). Use *enabled* to switch the browsing effect on or off, and use *browsingPressure* to globally scale the browsing probabilities associated with each species. Note that the browsing pressure can be modified during runtime (see [time events](time-events.qmd)).



### species parameter


The browsing submodule introduces a new species parameter, namely *browsingProbability*. This setting describes the annual probability that the saplings on a pixel (up to a height of 2m) are affected by browsing.


```
-- SQL code to create the new column
alter table species add column browsingProbability numeric;
update species set browsingProbability = 0.2;
```

