---
title: "competition for belowground resources"
---

Belowground competition is an important aspect of competitive plant interaction, yet is poorly represented in the majority of forest ecosystem models ([Le Roux et al. 2001](http://dx.doi.org/10.1051/forest:2001140)). Consequently, [Wullschleger et al. (2001)](http://dx.doi.org/10.1023/A:1012570821241) in their review of belowground processes in succession model strongly advocate an improved functional representation of roots and belowground competition in modeling (see also [Pages et al. 2000](http://dx.doi.org/10.1051/forest:2000138)).

Several approaches have been presented to simulate individual tree competition for soil water and nutrients, including an empirical parametrization of the belwoground competitive effect (e.g., [Canham et al. 2004](http://dx.doi.org/10.1139/X03-232)), the use of neighborhood-related concepts (e.g., [Chertov et al. 2003](http://dx.doi.org/10.1016/S0378-1127(02)00284-0), [Schwalm and Ek 2004](http://dx.doi.org/10.1016/j.ecolmodel.2004.04.016)), as well as detailed process-based models of resource use and competition (e.g., [Grote and Pretzsch 2002](http://dx.doi.org/10.1055/s-2002-25743), [Zavala et al. 2005](http://dx.doi.org/10.1016/j.ecolmodel.2005.05.006), [Gayler et al. 2006](http://dx.doi.org/10.1055/s-2006-923979)).

At this stage (v0.69), iLand focuses on aboveground competition for resources. This prioritizing is supported by the strong notion that aboveground competition is asymmetric whereas belowground competition is symmetric in forest ecosystems (e.g., [Cahill and Casper 2000](http://www.jstor.org/stable/3547141)). Nonetheless, in a possible next step of model development, belowground competition should be considered as candidate for inclusion. A possible approach could make use of the established structure of modeling above ground competition. [Casper et al. (2003)](http://dx.doi.org/10.1890/02-0287), for instance, present an approach based on a zone of influence / field of neighborhood approach that would be structurally suitable for implementation in iLand. Also the early approach of [King (1993)](http://treephys.oxfordjournals.org/cgi/reprint/12/2/119) would be a valuable starting point for developing such a module in iLand. Nonetheless, despite the considerable advances (cf. [Coomes and Grubb 2000](http://www.jstor.org/stable/2657174)) an immediate implementation might still be limited by data availability for parametrization since many conceptual models of root competition are developed for grassland species.