---
title: "contact information"
---



## contact


The [iLand](iland.qmd) main developers are [Rupert Seidl](http://www.wabo.boku.ac.at/seidl.html) and [Werner Rammer](http://www.wabo.boku.ac.at/rammer.html).

For questions concerning the science and ecology in iLand please contact
rupert *dot *seidl *at *boku *dot *ac *dot *at

For technical, developmental and software question, please contact
werner *dot *rammer *at *boku *dot *ac *dot *at




## website credits - legal notice


***responsible for content:***
Universität für Bodenkultur Wien
University of Natural Resources and Life Sciences, Vienna
Department of Forest- and Soil Sciences
Institute of Silviculture
1190 Vienna, Peter-Jordan-Straße 82
UID: ATU16285008

Rupert Seidl | Werner Rammer
rupert *dot *seidl *at *boku *dot *ac *dot *at | werner *dot *rammer *at *boku *dot *ac *dot *at
http://www.wabo.boku.ac.at/waldbau.html

basic direction of the medium: research dissemination
special legal regulation: [Universitätsgesetz 2002](http://www.boku.ac.at/fileadmin/_/H13/Projektsupport/UG2002dt_kurz.pdf)



