---
title: "Discussion and conclusion"
---

The analysis conducted here highlights the niche of the model under development in the current project and documented its neighbors in the landscape of models. It showed that a holistic ecosystem approach with regard to the indicators and dimensions of relevance to the overall objectives of the project has been scarcely taken in forest ecosystem modeling until now. The analysis, however, also indicates promising existing approaches in addressing the challenges in modeling resulting from such an approach. Particularly the models LANDIS-II and FireBGC give interesting reference points for the [iLand](iland.qmd) approach. Further noteworthy models and frameworks in this regard, not included in the current analysis, include LandClim ([Schumacher et al. 2004](http://dx.doi.org/10.1016/j.ecolmodel.2003.12.055)), TreeMig ([Lischke et al. 2006](http://dx.doi.org/10.1016/j.ecolmodel.2005.11.046)), SeibDVM ([Sato et al. 2007](http://dx.doi.org/10.1016/j.ecolmodel.2006.09.006)), and SELES ([Fall and Fall 2001](http://dx.doi.org/10.1016/S0304-3800(01)). Based on this analysis of complexity iLand is a relevant addition to the emerging set of forest ecosystem models for landscape level analysis of climate - disturbance - management interactions.