---
title: "dispersal"
---

The dispersal approach taken in iLand closely follows established landscape models such as LANDIS-II (see [Scheller and Domingo 2006](http://www.landis-ii.org/documentation/ModelDescription5.1.pdf), [Scheller et al. 2007](http://dx.doi.org/10.1016/j.ecolmodel.2006.10.009)) and TreeMig ([Lischke et al. 2006](http://dx.doi.org/10.1016/j.ecolmodel.2005.11.046)). While it doesn't keep track of seeds of individual trees explicitly (cf. [Lexer and Hoenninger 2001](http://dx.doi.org/10.1016/S0378-1127(00)00386-8), [Lischke et al. 2006](http://dx.doi.org/10.1016/j.ecolmodel.2005.11.046)) it assumes a probabilistic dispersal kernel around the grid cells containing mature trees.
The shape of the dispersal kernel is highly influential on migration and occupation success of tree species and has been intensively discussed in ecology (e.g., [Greene et al. 2004](http://dx.doi.org/10.1111/j.0022-0477.2004.00921.x)). LANDIS-II, for instance, uses a double exponential function ([Ward et al. 2004](http://www.landis-ii.org/documentation/DoubleExpSeed.pdf)), others found lognormal functions to be most suitable ([Greene et al. 2004](http://dx.doi.org/10.1111/j.0022-0477.2004.00921.x)), or applied a combination of functional forms to represent both zoochorous and wind dispersal ([Lischke et al. 2006](http://dx.doi.org/10.1016/j.ecolmodel.2005.11.046)). The default approach chosen for iLand is the two-part exponential dispersal kernel of [Lischke and Loeffler (2006)](http://dx.doi.org/10.1016/j.ecolmodel.2006.05.005), however, different functional forms can be used in the model, e.g. to study sensitivities.

The spatial entity of dispersal calculations is a continuous 20 x 20m grid over the landscape. Cells which are occupied by a mature tree (maturity being a threshold age for generative reproduction, specified as a [species parameter](species-parameter.qmd)) have the maximum probability of seed availability (cf. [He and Mladenoff 1999](http://www.jstor.org/pss/3659024)), with probabilities decreasing with distance according to the kernel function. Unlike the implicit scaling in LANDIS-II the probability kernel is scaled with species-specific [fecundity](fecundity.qmd), as fecundity has been found to be of high importance e.g. for long-distance dispersal ([Clark et al. 2001](http://www.jstor.org/stable/3078967)). Rather than applying dispersal kernels for individual trees we employ the kernel only once for a mature species per dispersal grid cell (cf. LANDIS-II). Kernels of individual cells occupied by seed trees are additively aggregated. A pattern-based approach along the lines of the [iLand light computation](competition-for-light.qmd) is used to spatially distribute and aggregated dispersal probabilities, i.e. we apply pre-processed dispersal kernels and scale them with fecundity.

The [fecundity](fecundity.qmd) of every tree/ regeneration patch is additionally modified for seed years, i.e. fecundity is reduced to a lower rate in non-seed years. Occurrence of seed years is computed following [Lexer and Hönninger (2001)](http://dx.doi.org/10.1016/S0378-1127(00)00386-8), randomly drawing seed years to match a mean seed year return interval specified per species in the [parameter set](species-parameter.qmd). In non-seed years the dispersal kernel is reduced by multiplying with a species-specific factor representing the reduced seed production in these years. iLand landscapes are sufficiently small that seed years can assumed to be synchronized across the whole simulated landscape, i.e. all individuals of the same species in the landscape experience a seed year synchronously (cf. [Koenig and Knops 2000](http://dx.doi.org/10.1086/303302)).

The probability for every cell, *p<sub>seed</sub>*, is subsequently used as proxy for seed availability in the calculation of [establishment](establishment.qmd). In iLand seeds, seed bank and seed predation are not simulated explicitly (cf. [Lischke and Loeffler 2006](http://dx.doi.org/10.1016/j.ecolmodel.2006.05.005)). Furthermore, resprouting is currently not implemented, but an approach along the lines of LANDIS-II ([Scheller and Domingo 2006](http://www.landis-ii.org/documentation/ModelDescription5.1.pdf)) could be included as needed.

The [seed kernel and seed distribution](seed-kernel-and-seed-distribution.qmd) page provdes further details. (Notes on the technical implementation for a previous version of iLand can be found ((regeneration - technical details (2010)|here)) ).




::: {.callout-note title="citation"}
[Seidl, R., Spies, T.A., Rammer, W., Steel, E.A., Pabst, R.J., Olsen, K. 2012](http://dx.doi.org/10.1007/s10021-012-9587-2). Multi-scale drivers of spatial variation in old-growth forest carbon density disentangled with Lidar and an individual-based landscape model. Ecosystems, DOI: 10.1007/s10021-012-9587-2.
:::
