---
title: "Introduction"
---

Determining the level of complexity is an important step in designing a model. A good model is a parsimonious one- it should contain all the complexity needed to address its specific aims but not more, an axiom also known as [Occam’s razor](http://en.wikipedia.org/wiki/Occam’s_Razor) (see for instance the discussion in [Kimmins et al. 2008](http://dx.doi.org/10.1016/j.foreco.2008.03.011)). Evidently, the process of simplifying reality in building a model, i.e. the determination of the appropriate level of complexity, is context-specific. Consequently there is no globally agreeable level of complexity and no “one size fits all” model for the variety of questions and applications that models can help to address.

The required level of model complexity for specific tasks has recently been quantitatively investigated by several studies, analyzing model behavior with different submodels of varying complexity (e.g.,[Astrup et al. 2008](http://dx.doi.org/10.1016/j.foreco.2008.07.016), [Kimmins et al. 2008](http://dx.doi.org/10.1016/j.foreco.2008.03.011)). Here the aim is to put the question of model complexity at the very beginning of model development, serving as a frame for the structural design of the model to be developed in the current study [(iLand](iland.qmd)). Choosing a relative definition of model complexity, i.e. relative to existing modeling approaches, this exercise is also designed to help defining the niche of iLand in the "landscape of established models" and highlight related approaches of relevance for iLand model development.

Acknowledging the importance of context for the determination of model complexity the starting point for this analysis is the projects intended aim and application. iLand should serve the analysis of forest dynamics under changing climate and disturbance regimes and project the interactions between climate (change), disturbance regimes and sustainable forest management. The framework aims at ecological generality, i.e. a general model structure applicable for a variety of temperate forest ecosystems, hence purely empirical models are excluded from the review of the current report.
