---
title: "landscape scale soil water dynamics"
---

Subsurface water flow dynamics and availability are strongly influenced by topography, particularly in forest landscapes characterized by complex and mountainous terrain. Such topographic effects on hydrology, influencing spatio-temporal characteristics of water availability, can be modeled quasi-distributed (i.e. statistical partitioning of watersheds into hydrologically similar areas, e.g., the TOPMODEL approach of [Beven and Kirkby 1979](http://iahs.info/hsj/240/hysj_24_01_0043.pdf)) or explicitly (i.e. simulating lateral flow between entities, e.g., the DHSVM approach of [Wigmosta et al. 1994](http://www.agu.org/journals/wr/v030/i006/94WR00436/)). [Band et al. (1993)](http://dx.doi.org/10.1002/hyp.253) and [Engel et al. (2002)](http://dx.doi.org/10.1016/S0304-3800(02)00068-6) give examples for an integration of the former approach within established ecophysiological frameworks that can be used to study spatio-temporal landscape level water cycling. Integrated ecosystem models using explicit soil water routing are still rare, although the work of [Tague and Band (2001)](http://dx.doi.org/10.1002/hyp.171) highlights the advantage of this approach in simulating spatially distributed soil moisture patterns.

In the current iLand version landscape scale water dynamics is not explicitly simulated. Different hydrological regimes within a forest landscape, e.g. influenced by topography, are represented solely by soil characteristics (e.g., differences in soil depth and soil physics) and climate input (e.g., precipitation levels, temperature-dependent snow water storage). A future improvement of the representation of the hydrological regime at the landscape level could be the adaption of the TOPMODEL approach into iLand, as implemented by [Band et al. (1993)](http://dx.doi.org/10.1002/hyp.253), [Zierl et al. (2007)](http://dx.doi.org/10.1002/hyp.6540). The approach of TOPMODEL, partitioning a watershed into hydrollogically homogeneous areas, would structurally correspond well with iLands model structure of resource units and sites.