---
title: "Object SpatialAnalysis"
---


::: {.callout-warning title="Note"}
The API documentation for this object moved: [Spatial Analysis object](../apidoc/classes/iland/spatialanalysis.qmd).
This page is deprecated, and will be removed.
:::


The SpatialAnalysis object exposes some special spatial functions built into iLand. The typical use-case is to extract some gridded data and save them to disk.



# *Methods*


**saveRumpleGrid(string filename)**
Calculate the Rumple-Index for the landscape with a spatial resolution of 10m (i.e., the cells of the iLand height grid) and extract a 100m grid (average over the 10m cells). Store the grid to *filename*.

**saveCrownCoverGrid(string filename)**
generate a map of crown covers (2m resolution), and save an average (100m) to *filename*. For each tree, the tree crown (as defined by the 'reader' stamp, which defines for 2m pixels the share of that pixels that is covered by a tree crown with a given tree crown radius) is additively plotted on a 2m grid. If that sum is larger then 0.5 (i.e. 50%), a pixel is consiedered as 'covered'. The resulting grid gives for each 100m a fraction of 'covered' pixels.



## Properties


**rumpleIndex**
The *rumpleIndex* property (read-only) is the value of the Rumple index for the whole landscape.