---
title: "primary production"
---

iLand uses a radiation use efficiency (*RUE*) approach (cf. [Medlyn et al. 2003](http://dx.doi.org/10.1071/FP02088)) to derive gross primary productivity at the canopy level, mainly following [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1). The target entity for this computation is the [resource unit](resource-units.qmd), taking into account individual tree [competition for light](competition-for-light.qmd).





# radiation interception


The fraction of intercepted photosynthetically active radiation above canopy (*pPAR*, dimensionless {0,1}) is calculated at the level of [resource units](resource-units.qmd) (i.e., ≈stands, or sites in the context of [LANDIS-II](http://www.landis-ii.org/)) by means of Beers law ([Lieffers et al. 1999](http://dx.doi.org/10.1139/cjfr-29-6-796)), Eq. (1):

$$
pPAR=1-e^{-k\cdot \frac{\sum_{j=1}^{n}LA_{j}}{SA}}
$$

with *LA<sub>j</sub>* the leaf area (m<sup>-2</sup>) of the *j<sup>th</sup>* individual on the resource units (*RU*) [#stocked_area|stocked area](resource-units.qmd) (*SA*, m<sup>2</sup>) and *k* the extinction coefficient. Total intercepted radiation at resource unit level is thus calculated by Eq. (2):

$$
APAR=PAR\cdot SA\cdot pPAR
$$

with *PAR *the photosynthetically active radiation per unit area (MJ∙m<sup>-2</sup>).

        *




# gross primary production


Gross primary production (*GPP*, gC) is the product of utilizable photosynthetic active radiation (*uAPAR*, MJ) and the effective radiation use efficiency (*ε<sub>eff</sub>*, g MJ<sup>-1</sup>), Eq. 3-5

$$
GPP=uAPAR\cdot \varepsilon _{eff}
$$


$$
uAPAR=APAR\cdot min(f_{temp}\: ;\:  f_{sw}\: ;\:  f_{VPD}) \cdot f_{age}
$$


$$
\varepsilon _{eff}=\varepsilon _{0}\cdot f_{N}\cdot f_{CO_{2}}
$$

with *f *denoting environmental modifiers and *ε<sub>0</sub>* the maximum radiation use efficiency. *GPP *is calculated monthly, to capture the intra-annual variability of the climate modifiers on *APAR* (Eq. 4).
The effect of the environment differs with species, i.e. the modifiers *f * are species-specifc. Furthermore, absorbed radiation of every individual depends on its leaf area as well as on the position in the canopy and radiation use strategy. Combining Eq. 3-5 with [#individual tree radiation|competition-based radiation partitioning at the level of individuals](individual-tree-light-availability.qmd) and species-specific environmental modifiers we compute individual tree *GPP*, while preserving consistency with the stand level approach of [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1).

        *




# environmental modifiers



* [temperature response](temperature-response.qmd)
* [soil water response](soil-water-response.qmd)
* [vapor pressure deficit response](vapor-pressure-deficit-response.qmd)
* [nitrogen response](nitrogen-response.qmd)
* [CO2 response](co2-response.qmd)
        *




# respiration and aging


We follow [Waring et al. (1998)](http://treephys.oxfordjournals.org/cgi/reprint/18/2/129) in assuming a constant respiration fraction of *GPP *to derive net primary production (*NPP*, Eq.6),

$$
NPP=GPP\cdot r
$$

with an respiration fraction *r* of 0.47 (cf. [Waring et al. 1998](http://treephys.oxfordjournals.org/cgi/reprint/18/2/129)). Although this simplified derivation of *NPP * is not undisputed (cf. , [Medlyn and Dewar 1999](http://treephys.oxfordjournals.org/cgi/reprint/19/2/137), [Mäkelä and Valentine 2001](http://treephys.oxfordjournals.org/cgi/reprint/21/14/1015)) it has proven to yield robust results in numerous applications. Moreover, implementing a more detailed approach to simulate autotrophic respiration would be beyond the scope of iLand.

Declining productivity potential with age is accounted for by [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1) by an aging modifier *(f<sub>age</sub>)*. While the original approach used age relative to a maximum attainable age as explanatory variable [Seidl et al. (2005)](http://treephys.oxfordjournals.org/cgi/reprint/25/7/939) in a similar approach substituted relative height for relative age. Empirical studies point towards a size (i.e. height)-related pattern of growth decline (e.g., [Bond et al. 2007](http://treephys.oxfordjournals.org/cgi/reprint/27/3/441)), *inter alia* as a result of hydraulic limitations (e.g., [Ryan et al. 2006](http://dx.doi.org/10.1111/j.1365-3040.2005.01478.x)). However, although hydraulic limitations with increasing size are common, no universal relationship has been found ([Ryan et al. 2006](http://dx.doi.org/10.1111/j.1365-3040.2005.01478.x)) and other factors, associated with physical age (e.g., [Munne-Bosch and Alegre 2002](http://dx.doi.org/10.1007/s004250100646)) might be relevant. [Niinemets (2002)](http://treephys.oxfordjournals.org/cgi/reprint/22/8/515), for instance, showed that both tree height and physical age were related to growth decline. A review over aging and remaining uncertainty in our understanding of growth decline processes is given by [Bond (2000)](http://dx.doi.org/10.1016/S1360-1385(00)01691-5).

Due to the limited process understanding and the intermediate process resolution in iLand we generally follow the simplified approach of [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1), applying an aging modifier (*f<sub>age</sub>*) to account for aging-related limitations on *NPP *(see Eq. 4).
Based on previous experiences within the [PICUS framework](http://www.wabo.boku.ac.at/picus.html?&L=1) we used both relative age (*age<sub>rel</sub>*) and relative height (*h<sub>rel</sub>*) to derive an indicator for a trees' age status, *AI* (Eq. 8, with *age<sub>rel</sub>* and *h<sub>rel</sub>* calculated as current age and height relative to the species-specific maximum). We applied a harmonic mean to combine the age- and height- related aging components and used their complementary values so that *AI* reaches 1 if any of the two components reaches its maximum (Eq. 8). *AI* was subsequently applied in the two-parameter function suggested by [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1) to derive the aging effect on productivity (Eq. 9).

$$
AI=1-\frac{2\cdot (1-age_{rel})\cdot (1-h_{rel})}{2-age_{rel}-h_{rel}}
$$

$$
f_{age}=\frac{1}{1+(\frac{AI}{m_{age}})^{n_{age}}}
$$

where *m<sub>age</sub>* and *n<sub>age</sub>* the empirical constants. Unlike [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1), *f<sub>age</sub>* is calculated and applied at the level of individual trees in iLand. We used the values of [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97)00026-1) as starting points for the latter, a re-parametrization to observed values might, however, be necessary at a later point. Using a composite of relative age and size allows for an aging effect in both fast growing stands (where mostly relative height drives *f<sub>age</sub>*) and on poor sites (i.e. where the maximial attainable height is far below the species maximum), where a gradual age decline is induced by the linearly increasing physical age.




::: {.callout-note title="citation"}
[Seidl, R., Rammer, W., Scheller, R.M., Spies, T.A. 2012](http://dx.doi.org/10.1016/j.ecolmodel.2012.02.015). An individual-based process model to simulate landscape-scale forest ecosystem dynamics. Ecol. Model. 231, 87-100.
:::


