---
title: "Scripting"
---

This page is a hub for scripting, that provides links to Javascript (general) and all the APIs and iLand-objects made available via scripting as well as sample programs.
Click here, for [general concepts](iland-scripting.qmd) of how the models behavior can be influenced by scripting.

The iLand Scripting API page:[iland-model.org/apidoc/index.html](../apidoc/index.qmd)
^We recently (2016) remodeled the API-documentation: since the start of iLand, the Javascript API was located on specific wiki pages (e.g., [Globals](../apidoc/classes/iland/globals.qmd)). The new system puts the documentation of the API closer to the source code (i.e. within the source code tree), and uses [YUIdoc](http://yui.github.io/yuidoc/) to generate the documentation pages (with better cross links, better syntax highlighting, etc.).

The transition is, unfortunately, not fully complete, and you still find some parts of the API documentation in the wiki.
^
 



## API Documentation




### [iland-model.org/apidoc](http://iland-model.org/apidoc/modules/iLand.html)



The API document page describes the following objects:

* Globals
* Grid
* Managemenet
* Map
* Factory
* SpatialAnalysis

Still on the Wiki:
**[ClimateConverter](object-climateconverter.qmd)**
Helper class to import climate data from various text sources.




## scripting in modules


[wind+module](wind-module.qmd)
Access to functions of the iLand [wind module](wind-disturbance.qmd).

[fire+module](fire-module.qmd)
access to functiond of the iLand [wildfire] module.

[barkbeetle+module](barkbeetle-module.qmd)
access to functions of the iLand [barkbeetle] module.



## Examples


[management example: parallel management](management-example-parallel-management.qmd)
[management example: HJA fire history](management-example-hja-fire-history.qmd)
((management example: restoration area (modern Javascript) ))
