---
title: "sprouts"
---

iLand includes a basic support for the resproting of trees. The sprouting behavior (i.e., multiple new trees grow from the stump of a harvested tree) can be enabled for individual tree species. The basic effect of resprouting is the establishment of new cohorts after tree harvests (or disturbance), and faster height growth of those cohorts.  Sprouts are established without taking into account the establishment filters (i.e., the climatic and water filters are circumvented). Sprouting is triggered when (the [species parameter](species-parameter.qmd)) “*sapSproutGrowth*” is a positive number, and the parent tree is either removed by management or due to disturbance (all agents). A sprouting cohort is always established at the 2x2 m pixel of the parent tree. A sprouting cohort is also established when a sapling (cohort) with a height above a threshold (currently 1m) is disturbed (fire / wind) or harvested. 

Lateral clones of sprouting trees are handeld as follows: An tree >4m can sprout to adjacent 2x2m pixels every year with a probability given by the *model.species.sprouting.adultSproutProbability* key in the [project file](project-file.qmd). If none of the 8 neighboring pixels is suitable (=not already populated with sprouts of that species) no sprouting is simulated. If a single value is given for *adultSproutProbability, *the value is used for all species. Species-specific values can be provided as a list of species Ids and probabilities (similar to the setting [#Using_external_seed_input_on_the_whole_area|externalSeedBackgroundInput](external-seeds.qmd)).

The actual height growth of sprouted cohorts ($i_H$ in Eq 4 [here](sapling-growth-and-competition.qmd)) is multiplied by the species parameter (“*sapSproutGrowth*”). Actually, the relative height growth (i.e., environment response * light response, a value between 0 and 1) is modified (see also [#height_growth](sapling-growth-and-competition.qmd)). This has the consequence that sprouts are less prone to stress (and thus mortality), as the (increased) relative height is compared against the species-specific threshold to determine the stress status of a sapling. Furthermore, the height growth of a sapling can exceed the height growth potential given for the species. Whenever a cohort reaches the height of 4m, individual trees are created, which behave exactly like non-sprouted trees (e.g., there is no effect on e.g., root biomass). The effect of increased height growth of sprouts can be best tracked/ tested using the “Sapling growth” debug output ([Debug output](debug-outputs.qmd)). Note, that the output contains average values per resource unit and species (and not data for individual cohorts). However, the effect should be visible when looking at the average height growth, and the duration between establishment (cohorts appearing under “Added”) and recruitment (“Recruited”-column).

 