---
title: "Class: CSVFile"
sidebar: apidoc
---

# CSVFile Class

The `CSVFile` is a helper class to load and process tabular data which is stored in a text file.

The type of delimiter is auto-detected from the first lines of the file. Possible delimeters are `;`, `,`, a tabulator (\t) or space(s).

Lines beginning with `#` are and empty lines are ignored. Quotes around (`"`) values are removed. Both Linux (\n) and Windows (\r\n) line ending characters are supported.

All indices are 0-based (e.g., valid rows are 0..rowCount-1).

Example
-------

```javascript
    var csv = new CSVFile(""); // do not load a file

    csv.loadFromString('a;b;c\n1;2;3\n1;4;12.1'); // note the newline characters
    console.log( csv.value(1,2) ); // -> 12.1

    // change a value
    csv.setValue(csv.rowCount-1,csv.columnIndex('a'), 100);
    csv.saveFile(Globals.path('temp/test.csv'));

    var csv = new CSVFile( Globals.path('temp/test.csv') );
    console.log( csv.value(1,"c") ); // -> 12.1
    console.log( csv.row(0) ); // get the full row (including delimiters)

    // loop over all rows
    for (var i=0;i<csv.rowCount;++i)
        console.log( csv.value(i,0) );
```

## Properties Overview

| Name | Type | Description |
| :--- | :--- | :--- |
| [`captions`](#captions) | `bool` | if `true`, then the first line of the input file are considered to be headers. Default: `true`. |
| [`colCount`](#colcount) | `integer` | The number of columns in the table (-1 if not loaded). |
| [`flat`](#flat) | `bool` | if `true`, it is assumed that the file contains only one column (default: false). |
| [`rowCount`](#rowcount) | `integer` | The number of rows in the table (-1 if not loaded). |

## Methods Overview

| Method | Return Type | Description |
| :--- | :--- | :--- |
| [`columnIndex(colName)`](#columnindex) | `integer` | Retrieve the index of the column with the name `colName`. The index can be used in later call to `value()`. The functions returns -1 if the column is not present. |
| [`columnName(col)`](#columnname) | `string` | Retrieve the column name with the index `col`. |
| [`jsValue(row)`](#jsvalue) | `value` | Retrieve the value of the column `colName`and the row with the index `row`. |
| [`jsValue(row)`](#jsvalue-1) | `value` | Retrieve the value of the column with the index `col`and the row with the index `row`. The return value is a string value. The javascript built-in function `Number` can be used to force a conversion to a numerical value. |
| [`loadFile(fileName)`](#loadfile) | `void` | Load a table from the file given in `fileName`. The delimiter is autodetected (see above). |
| [`loadFromString(content)`](#loadfromstring) | `bool` | Load a table from a string. The delimiter is autodetected (see above). Use newline characters (`\n`) to separate lines. Captions |
| [`saveFile(fileName)`](#savefile) | `void` | Save the current state of the table to a file with the name `fileName`. |
| [`setValue(row)`](#setvalue) | `void` | Change the value of the cell with in the column with the index `col`and the row with the index `row`. The new value can be either a numeric or a string. |
| [`value(row)`](#value) | `string` | Retrieve the value of the column `colName`and the row with the index `row`. |
| [`value(row)`](#value-1) | `string` | Retrieve the value of the column with the index `col`and the row with the index `row`. The return value is a string value. The javascript built-in function `Number` can be used to force a conversion to a numerical value. |

## Properties Details

### `captions` {#captions}

<span class="api-tag tag-type">bool</span>

if `true`, then the first line of the input file are considered to be headers. Default: `true`.

```javascript
    See also: [columnIndex()](csvfile.qmd#columnindex)
```

---

### `colCount` {#colcount}

<span class="api-tag tag-type">integer</span>

The number of columns in the table (-1 if not loaded).

---

### `flat` {#flat}

<span class="api-tag tag-type">bool</span>

if `true`, it is assumed that the file contains only one column (default: false).

---

### `rowCount` {#rowcount}

<span class="api-tag tag-type">integer</span>

The number of rows in the table (-1 if not loaded).

---

## Methods Details

### `columnIndex(colName)` {#columnindex}

**Returns:** `integer`

Retrieve the index of the column with the name `colName`. The index can be used in later call to `value()`. The functions returns -1 if the column is not present.

**Parameters:**

*   **`colName`** (`string`): a column name
    @return {integer} the index of the given column, or -1 if the column is not available.

**Return Value Description:** the index of the given column, or -1 if the column is not available.

---

### `columnName(col)` {#columnname}

**Returns:** `string`

Retrieve the column name with the index `col`.

**Parameters:**

*   **`col`** (`integer`): a valid column index (0<=index<colCount).
    @return {string} the column name

**Return Value Description:** the column name

---

### `jsValue(row)` {#jsvalue}

**Returns:** `value`

Retrieve the value of the column `colName`and the row with the index `row`.

**Parameters:**

*   **`row`** (`integer`): row index of the value to retrieve (0<=row<rowCount).
    @param {string} colName  a column name
    @return {value} the value (either int, double, or string converted from the input)

**Return Value Description:** the value (either int, double, or string converted from the input)

---

### `jsValue(row)` {#jsvalue-1}

**Returns:** `value`

Retrieve the value of the column with the index `col`and the row with the index `row`. The return value is a string value. The javascript built-in function `Number` can be used to force a conversion to a numerical value.

```javascript
See also: [columnIndex()](csvfile.qmd#columnindex),[value()](csvfile.qmd#value)
```

**Parameters:**

*   **`row`** (`integer`): row index of the value to retrieve (0<=row<rowCount).
    @param {integer} col column index of the requested value (0<=col<colCount).
    @return {value} the value as a Javascript value (int, double, or string)

**Return Value Description:** the value as a Javascript value (int, double, or string)

---

### `loadFile(fileName)` {#loadfile}

**Returns:** `void`

Load a table from the file given in `fileName`. The delimiter is autodetected (see above).

**Parameters:**

*   **`fileName`** (`string`): file to load (Use [path()](globals.qmd#path) for using relative paths).
    @return { bool } `true` on sucess

---

### `loadFromString(content)` {#loadfromstring}

**Returns:** `bool`

Load a table from a string. The delimiter is autodetected (see above). Use newline characters (`\n`) to separate lines. Captions

**Parameters:**

*   **`content`** (`string`): string that should be interpreted as a table.
    @return {bool} `true` on sucess

**Return Value Description:** `true` on sucess

---

### `saveFile(fileName)` {#savefile}

**Returns:** `void`

Save the current state of the table to a file with the name `fileName`.

```javascript
See also: [loadFile()](csvfile.qmd#loadfile), [loadFromString()](csvfile.qmd#loadfromstring)
```

**Parameters:**

*   **`fileName`** (`string`): file to be created or overwritten (Use [path()](globals.qmd#path) for using relative paths).
    @return { bool } `true` on sucess

---

### `setValue(row)` {#setvalue}

**Returns:** `void`

Change the value of the cell with in the column with the index `col`and the row with the index `row`. The new value can be either a numeric or a string.

```javascript
See also: [value()](csvfile.qmd#value)
```

**Parameters:**

*   **`row`** (`integer`): index of the value to retrieve (0<=row<rowCount).
    @param {integer} col column index of the requested value (0<=col<colCount).
    @param {variant} newValue  new value (either a string or numeric).

---

### `value(row)` {#value}

**Returns:** `string`

Retrieve the value of the column `colName`and the row with the index `row`.

**Parameters:**

*   **`row`** (`integer`): row index of the value to retrieve (0<=row<rowCount).
    @param {string} colName  a column name
    @return {string} the value (use Javascript's `Number()` to convert to a number)

**Return Value Description:** the value (use Javascript's `Number()` to convert to a number)

---

### `value(row)` {#value-1}

**Returns:** `string`

Retrieve the value of the column with the index `col`and the row with the index `row`. The return value is a string value. The javascript built-in function `Number` can be used to force a conversion to a numerical value.

```javascript
See also: [columnIndex()](csvfile.qmd#columnindex),[jsValue()](csvfile.qmd#jsvalue)
```

**Parameters:**

*   **`row`** (`integer`): row index of the value to retrieve (0<=row<rowCount).
    @param {integer} col column index of the requested value (0<=col<colCount).
    @return {string} the value (use Javascript's `Number()` to convert to a number)

**Return Value Description:** the value (use Javascript's `Number()` to convert to a number)

---

