---
title: "Class: thinning"
sidebar: apidoc
---

# thinning Class

The thinning module include activities thinning operations.

## Methods Overview

| Method | Return Type | Description |
| :--- | :--- | :--- |
| [`fromBelow(options)`](#frombelow) | `object` | Thinning from below |
| [`plenter(options)`](#plenter) | `object` | Plenter thinning operation |
| [`tending(options)`](#tending) | `object` | Tending operation |

## Methods Details

### `fromBelow(options)` {#frombelow}

**Returns:** `object`

Thinning from below

**Parameters:**

*   **`options`** (`object`): @param {string} options.id A unique identifier for the thinning activity (default: 'ThinningFromBelow').
   @param {object} options.schedule schedule for the repeater (default: {min: 30, opt: 40, max: 50}).
   @param {number} options.interval interval between repeated thinnings (default: 5).
   @param {number} options.times number of times to repeat the thinning (default: 5).
   @param {boolean} options.block block other activities in repeater (default: true).
   @param {string} options.mode mode of thinning, either 'simple' or 'dynamic' (default: 'simple').
   @param {number|function} options.thinningShare share of trees to be thinned, can be a number or a function returning a number (default: 0.1).
   @param {number[]} options.thinningClasses array defining how much of each thinning class should be removed (default: [60, 25, 15, 0, 0]).
   @param {number|undefined} options.speciesSelectivity species list, which species should have a lower probability to get harvested (default: undefined).
   @param {string} options.ranking ranking string for filtering trees, e.g. 'volume' (default: 'volume').
   @param {string} options.sendSignal signal for triggering the thinning (default: 'thinning_execute').
   @param {string|undefined} options.constraint constraint (default: undefined).

**Return Value Description:** program - An object describing the thinning program

**Example:**

```javascript
lib.thinning.fromBelow({
        schedule: { min: 25, opt: 35, max: 45 },
        interval: 10,
        thinningShare: 0.3
    });
```

---

### `plenter(options)` {#plenter}

**Returns:** `object`

Plenter thinning operation

**Parameters:**

*   **`options`** (`object`): @param {string} options.id A unique identifier for the thinning activity (default: 'Plenter').
   @param {object|undefined} options.schedule schedule for the thinning (default: undefined).
   @param {number} options.times number of thinning actions (default: 1000).
   @param {number} options.interval interval between thinning actions (default: 5).
   @param {object} options.plenterCurve object defining target diameter distribution i.e. plenter curve.
   @param {number} options.dbhSteps width of dbh classes to compare with plenterCurve (default: 5).
   @param {number} options.intensity intensity of thinning activity, specifying which share of trees to remove should be removed (default: 1).
   @param {boolean} options.block block other activities in repeater (default: true).
   @param {string} options.sendSignal signal for triggering the thinning (default: 'plenter_execute').
   @param {string|undefined} options.constraint constraint (default: undefined).

**Return Value Description:** program - An object describing the plenter thinning program

**Example:**

```javascript
lib.thinning.plenter({
        interval: 5,
        plenterCurve: { 10: 350, 20: 150, 30: 80, 40: 40, 50: 20 },
		   dbhSteps: 10
    });
```

---

### `tending(options)` {#tending}

**Returns:** `object`

Tending operation

**Parameters:**

*   **`options`** (`object`): @param {string} options.id A unique identifier for the tending activity (default: 'Tending').
   @param {object|undefined} options.schedule schedule for the tending (default: undefined).
   @param {number} options.times number of tending actions (default: 3).
   @param {number} options.interval interval between tending actions (default: 2).
   @param {object} options.speciesSelectivity object defining species selectivity, e.g. { 'fasy': 0.9, 'abal': 0.8, 'rest': 0.2 } (default: { 'rest': 0.9 }).
   @param {number} options.intensity intensity of tending (default: 10).
   @param {boolean} options.block block other activities in repeater (default: true).
   @param {string} options.sendSignal signal for triggering the tending (default: 'tending_execute').
   @param {string|undefined} options.constraint constraint (default: undefined).

**Return Value Description:** program - An object describing the tending program

**Example:**

```javascript
lib.thinning.tending({
        times: 5,
        interval: 3,
        speciesSelectivity: { 'piab': 0.7, 'lade': 0.6 }
    });
```

---

