---
title: "Diversity mitigates disturbance impact"
date: "2015-06-25"
author: "Rupert Seidl"
---

The relationships and interactions between biodiversity and disturbance have long been a focus of ecological research ([Connell 1978](http://www.ncbi.nlm.nih.gov/pubmed/17840770), [Grime 1979](https://books.google.at/books?id=xX6v45bGGlkC&amp;lpg=PA335&amp;ots=0aila61y1z&amp;dq=Plant)). Furthermore, recent research has shown that biodiversity is the backbone for the provisioning of many important ecosystem services. One of the major hypothesis here is known as the insurance hypothesis ([Yachi and Loreau 1999](http://www.pnas.org/content/96/4/1463.short)), which postulates that diversity buffers against fluctuations and disruptions. This has been shown conclusively for grassland ecosystems (see e.g., [Cardinale et al. 2013](http://www.esajournals.org/doi/abs/10.1890/12-1334.1)), and is also implied for forests (where managers are frequently advised to propagate mixed forests to hedge against risks). Yet, how big this effect is, and if it changes over stand development (which is considerably more complex in forests compared to grassland ecosystems) remain big question marks.

Which is where iLand comes in. There are tremendous efforts to study diversity effects empirically and experimentally ([Baeten et al. 2013](http://www.sciencedirect.com/science/article/pii/S1433831913000553)), yet a comprehensive analysis over a large gradient of diversity levels covering centennial time scales is to date only possible in silicio. Within the framework of the [FunDivEUROPE project](http://www.fundiveurope.eu/) we thus set up an analysis to study if and how tree species diversity mediates the impact of disturbances on the forest carbon cycle with iLand (ht to [Mariana Silva Pedro](http://www.wabo.boku.ac.at/waldbau/personen/pedro/), who’s actually done all the hard work).

We found that – as predicted by the insurance hypothesis – more diverse forests experienced a lower negative impact of disturbances on the C cycle. One particularly interesting finding was that this effect increased in strength with increasing disturbance impact, suggesting that diversity is at least partly able to buffer forests from the impacts of intensifying disturbance regimes (see [Seidl et al. 2014](http://www.nature.com/nclimate/journal/v4/n9/abs/nclimate2318.html)). Also the predictability of the system increased with diversity, or, in other words, its stochasticity decreased, which is an important factor for a continuous provisioning of ecosystem services.

Interestingly, however, these effects were more pronounced in early seral stages of forest development, and weakened or even reversed in late seral forests. Competitive exclusion and diverging successional trajectories were responsible for this result, which underlines that diversity – disturbance relationships in forests are considerably more complex than in grassland systems. [Here’s the link](http://link.springer.com/article/10.1007/s00442-014-3150-0) to the paper in case you want to know more.
