---
title: "iLand v0.69: what's new?"
date: "2012-09-28"
author: "Rupert Seidl"
---

So, as already mentioned by Werner over at the [tech blog](blogpost39-iland-069-the-new-kid-on-the-block.qmd), we're happy to announce the release of a new iLand version (v0.69). This release marks the publication of another major iLand paper (read more about it [here](blogpost38-gauging-forest-carbon-with-iland.qmd)). While my [previous post](blogpost38-gauging-forest-carbon-with-iland.qmd) should give you an idea about what this new version is capable of and what it can be used for, I briefly want to highlight the major changes from the previously released version in this post.
In a nutshell, iLand v0.69 is the first release that has full dynamic landscape modeling capabilities (i.e., simulates the major demographic processes of growth, mortality, and regeneration), and simulates a closed carbon (C) cycle (i.e., accounts of both above- and belowground forest C compartments). The major changes from the previously released version thus relate mostly to the inclusion of dynamic regeneration and soil modules.



## Regeneration modeling


We followed the general recommendation of [Price et al. (2001)](http://dx.doi.org/10.1023/A:1012579107129) to address the main processes associated with forest regeneration explicitly. This means that iLand explicitly addresses the processes of [seed dispersal](../wiki/dispersal.qmd) (in space and time), the [germination and establishment](../wiki/establishment.qmd) of trees, as well as the [growth and competition of saplings](../wiki/sapling-growth-and-competition.qmd). The technical details can be found at the respective [model documentation wiki](../wiki/iland-hub.qmd) pages. Here are some more general thoughts on the regeneration modeling in iLand. One of the big challenges was how to address the potentially very large number of seedlings and saplings at the landscape scale in an efficient manner, while still maintaining the ability to capture the structure heterogeneity and spatial complexity associated with regeneration dynamics (cf. the initial [objectives of model design](../wiki/model-design.qmd) in the iLand wiki history section.). In order to address this challenge we applied a (computationally efficient) mean tree approach to model seedlings and saplings at a high spatial resolution of 2 x 2 meters. This approach allows us to model inter-specific height growth competition in the regeneration layer explicitly, while it is very sensitive to the type (e.g., management, wildfire), size (small gap vs. large clearing), and location (relative to seed trees) of canopy disturbances. To account for the effect of the latter on regeneration we again used iLand's detailed [light simulation routine](../wiki/competition-for-light.qmd) and the continuous light influence field calculated by the model at the landscape scale - with great success, as attested by the evaluation conducted in [Seidl et al. (2012b)](http://dx.doi.org/10.1007/s10021-012-9587-2). Overall, the model is sensitive to climate, and is able to reproduce both the temporal patterns of species succession as well as the spatial patterns of light-driven regeneration in temperate forest ecosystems.




## Soil and decomposition modeling


The main objectives with regard to modeling decomposition and soil processes were to select an approach that

* consistently simulates effects of climate change, management and disturbances on soil C stocks, and
* allows first order plant-soil feedbacks with regard to nutrient availability.

The challenge here was to select an approach that is robust and tractable in landscape scale simulations. In this regard, the selection of a relatively simple model was supported by a recent meta-analysis by [Manzoni and Proporato (2009)](http://dx.doi.org/10.1016/j.soilbio.2009.02.031), who found that for modeling general soil processes &lt;5 state variables suffice (whereas a considerably higher model complexity is required for modeling certain soil aspects with a high level of detail). After reviewing the literature and analyzing seven soil modeling approaches in detail (i.e. Standcarb, TRACE, YASSO07, CENTURY, Biome-BGC, LPJ, the ICBM-family), particularly contrasting their designs and abilities with the above mentioned objectives, we adopted the ICBM/2N approach as the soil C and N cycling module in iLand. ICBM/2N was developed as a relatively simple, analytically solvable model to study climate and management effects on soil C (Andrén and Kätterer 1997). The iLand soil and decomposition model accounts for eight detritus pools, i.e., snags, downed woody debris, litter, and soil organic matter for both C and N.
An important issue in the context of simulating forest soil dynamics is the initialization and parameterization of soil models, since high quality soil data with continuous coverage are rarely available in potential study landscapes. In this regard the new iLand soil module was designed to flexibly use the available data while not constraining the models' applicability in cases where wall-to-wall soil data coverage is not available for a study region. The model can thus be initialized with empirical data where available, but can also be spun-up to derive initial C and N pools from the simulation itself (see [here](../wiki/soil-parametrization-and-initialization.qmd)for more details). Also, it can be used both with N feedbacks on plant growth simulated dynamically and using an externally derived [fertility rating](http://dx.doi.org/10.1139/X05-089) (which can be hand for analytical purposes, see e.g. [here](http://dx.doi.org/10.1007/s10021-012-9587-2)). To test the model we compared simulations against observed C stocks at the HJ Andrews Experimental Forest, finding good agreement between simulation results and empirical data ([Seidl et al. 2012b](http://dx.doi.org/10.1007/s10021-012-9587-2)).

In summary, iLand v0.69 marks a major milestone in the development of iLand, and presents the first release that is capable of simulating closed C cycles and full forest landscape dynamics. If you want to try it out just head over [here](../wiki/download.qmd) and download a copy - we've included a test landscape which allows you to run the model out of the box! Next up in iLand world: a focus on disturbance modules (e.g, [wind](blogpost30-frontiers-in-modeling-wind-disturbance.qmd), [wildfire](blogpost32-the-fire-season-is-still-on.qmd)), and more applications, finally getting around to using the model to answer some of the questions it was originally developed for. Stay tuned!
