---
title: "How much complexity is enough?"
date: "2010-02-10"
author: "Rupert Seidl"
---

I guess that’s a question most if not all modelers have to deal with at some point. Because quite contrary to the first intuition it’s not making a model more complex that’s challenging but vice versa (see for instance David Mladenoffs notion on the issue [here](http://dx.doi.org/10.1016/j.ecolmodel.2004.03.016)). A model is per definition ***a simplified representation of reality***, so modeling is always about reducing a complex reality into something more traceable, analytically solvable and computationally implementable. The gentle art is though to find the level of complexity that’s sufficient to address the system traits relevant for the question at hand (NB that every model is context-specific, so there is no universal ‘world model’, as it would have to be as complex as the ‘world’ itself and would thus be no more simplification of reality… [here](http://rs.resalliance.org/2010/01/08/remnants-of-the-biosphere/) is a nice piece about the utopian attempt to create exactly that, a full-blown model of the biosphere, and where it stands today after 25 years and 200 million $... but I’m deviating]).
So the decision about complexity is probably the single most important task in modeling, but what is the right level of complexity? Albert Einstein maintained that a model should be ***as simple as possible, but not simpler***. As good as this axiom sounds, where does it leave us? Recently [some](http://dx.doi.org/10.1016/j.foreco.2008.03.011) [colleagues](http://dx.doi.org/10.1016/j.foreco.2008.07.016) used modular model designs to scrutinize this question quantitatively, i.e. add levels of complexity and scrutinize the influence on model behavior with regard to certain aspects of interest. In [iLand](../wiki/iland.qmd) we’ve been putting exactly this question of complexity at the core of model development.
Complexity in ecosystems is more and more recognized as not just another trait or way to describe systems. It is essentially at the core of their functioning (as has been recently shown by [colleagues here at OSU](http://dx.doi.org/10.1890/08-0073.1)). Consequently, complexity is even recommended to be a central issue in our management considerations; ***“managing for complexity”*** is what [Klaus Puettmann and colleagues](http://tinyurl.com/yksnulu) see as the main challenge for a modern silviculture. To develop a model that supports this task, we need to embrace complexity and its functional, structural and spatial dimensions in ecosystems. The [iLand](../wiki/iland.qmd) model design is inter alia motivated by the limitations of previous approaches to address these three levels of complexity simulatenously in a dynamic modeling framework (more on context and approaches in the review contained in the first [iLand-related publication](http://dx.doi.org/10.1007/s00267-009-9414-5))… Stay tuned on how we tackled this challenge and why we think it is important!
