---
title: "New iLand projects"
date: "2013-02-05"
author: "Rupert Seidl"
---

It’s a new year (well, sort of… by now we’re through 10% of 2013 already, sigh), and what better way to start off the new blogging season with introducing two new (iLand-related) research projects that are starting up here at [BOKU, Vienna](http://www.boku.ac.at/):

The first one, entitled “[Agent-based MOdeling of Climate Change Adaptation in forest management](https://forschung.boku.ac.at/fis/suchen.projekt_uebersicht?sprache_in=de&amp;menue_id_in=300&amp;id_in=9549)” (MOCCA) and funded by the [Austrian Climate and Energy Fund ACRP](http://www.klimafonds.gv.at/), will be focusing on the development of an agent-based management module for iLand. The aim is to better be able to simulate managed forest ecosystems, and include adaptive behavior of managers (e.g. to dynamically changing disturbance regimes) into the simulations. Our main motivation and hypothesis is that considering purely prescriptive management in simulations only (as we’ve [done previously](http://dx.doi.org/10.1016/j.foreco.2008.04.002)) might lead to an underestimation of resilience. The project thus will not only be a major next step in developing iLand further, but will also apply the model to address questions of how to robustly manage forest ecosystems under the uncertainty of changing climate and disturbance regimes. We will start MOCCA in March 2013, and are delighted that we’ll be collaborating with [Bernhard Wolfslehner](http://www.eficeec.efi.int/portal/about_eficeec/eficeec_staff/) (EFICEEC-EFISEE) and [Kristina Blennow](http://www.slu.se/en/faculties/ltj/about-the-faculty/departments/landscape-architecture/staff/kristina-blennow/) (SLU) in its implementation.

The second grant we’ve just got accepted is “Simulating Adaptation of forest manaGement to changing climate and disturbancE regimes” (SAGE), and it’s an European Union FP7 [Marie Curie Career Integration Grant](http://ec.europa.eu/research/mariecurieactions/about-mca/actions/cig/index_en.htm) (CIG) awarded to me (Rupert). As you can see already from the title, we’ll be working on issues closely related to MOCCA also under this grant – CIGs in general are conceived as additional funding, intended to bolster researchers starting up their own group at a new host/ new position. The CIG will allow us to go considerably beyond what we proposed for MOCCA. It will enable us to pursue investigations on disturbance interactions with iLand, study disturbance – climate relationships also at larger scales (in collaboration with [Mart-Jan Schelhaas](http://www.wageningenur.nl/en/Persons/dr.ir.-M-MartJan-Schelhaas.htm), Alterra), and continue our iLand-based work on resilience and complexity in forests ecosystems of the US Pacific Northwest (together with [Tom Spies](http://fes.forestry.oregonstate.edu/faculty/spies-tom)). So SAGE will contribute considerably to advancing our research on disturbance dynamics and resilience to disturbances in forest management, and will also bring about a number of new and exciting iLand applications.

So overall we’ve had a quite good start into 2013, and are very much looking forward to diving into the questions and materials of these two new projects. We’ll keep you updated on the progress as we go. And, just in case you were wondering: We’ll of course continue our strict [open source policy](../wiki/iland-software-and-source-code.qmd) also under MOCCA and SAGE, and will eventually make our new developments (code, executables, etc.) publicly available through this website – stay tuned!