---
title: "iLand v0.7 release notes"
date: "2013-10-22"
author: "Rupert Seidl"
---

We’re happy to announce the release of a new iLand version, the first release that includes a full dynamic, process-based disturbance module.

iLand is now able to simulate wind disturbance, driven by weather conditions and the dynamically simulated forest structure and composition, with damage extent, pattern, distribution and severity being emergent properties of the simulation. The iLand wind module takes a process-based dose-response approach, described in detail [here](../wiki/wind-disturbance.qmd). A particular novelty of the approach is that wind events (and their shape, size, severity) are not imposed on the landscape, but that forest structure is updated during a wind event. The dynamic changes in stand edges and exposure within a wind event are taken into account in the simulation, thus simulating the “spread” of a wind disturbance in the landscape explicitly.

Furthermore, the new wind disturbance module makes extensive use of iLands high resolution with regard to vegetation characteristics. Rather than executing the process-based dose-response calculations at the stand-level (represented by a mean tree, as done in many previous models, see [here for a review](http://dx.doi.org/10.1016/j.ecolmodel.2010.09.040) of wind disturbance modeling) we scale these calculations down to the level of dominant individual trees in iLand. This not only yields higher fidelity in the delineation of wind impact, it also allows the consideration of structured and uneven-aged stand conditions with regard to wind risk. A [case study for the a landscape in southern Sweden](http://dx.doi.org/10.1016/j.envsoft.2013.09.018) showed that disregarding the tree-level heterogeneity in wind modeling can lead to a considerable underestimation of wind damage, underlining the utility of high resolution vegetation information for disturbance modeling.

A peer-reviewed paper describing the development and testing of the new iLand wind module can be found [here](http://dx.doi.org/10.1016/j.envsoft.2013.09.018). More details on the [concept](../wiki/wind-disturbance.qmd) and [technical implementation](../wiki/wind-module.qmd) as well as the results of an extensive [sensitivity analysis](../wiki/wind-module-sensitivity-analysis.qmd) are available in the iLand wiki. As usual, the new version is available for download in the [download section](../wiki/download.qmd). Please note that all the previous functionality of the model is retained in this new model version. Also, the wind module can be disengaged for situations and research questions where wind is of no relevance.

If you have questions or comments on this new release we’d be happy to hear from you (please contact [our team](../wiki/team.qmd)). In the meanwhile we’ll continue our work to include additional disturbance processes in iLand (next up: [forest fires](blogpost42-iland-is-burning.qmd)), while increasingly using the model as a potent tool to answer our current [research](https://forschung.boku.ac.at/fis/suchen.projekt_uebersicht?sprache_in=en&amp;ansicht_in=&amp;menue_id_in=300&amp;id_in=9601) [questions](https://forschung.boku.ac.at/fis/suchen.projekt_uebersicht?sprache_in=en&amp;ansicht_in=&amp;menue_id_in=300&amp;id_in=8592).
