---
title: "Cause of death – unknown"
date: "2009-09-14"
author: "Rupert Seidl"
---

Mortality (for this posting: tree death due to causes other than disturbance and management) is a very important process in forest ecosystem dynamics- yet our understanding of causes and triggers of individual tree mortality is still poor. Despite all efforts, we’re mostly limited to recording a trees’ demise, for instance in inventories or from remote sensing data, but its [cause of death](http://en.wikipedia.org/wiki/Forensic_science) remains widely unknown. Consequently, [modeling the process of tree mortality](http://dx.doi.org/10.1023/A:1012539409854) has received much less attention than, for instance, growth, and models have been mostly [“well designed”](http://dx.doi.org/10.1016/j.ecolmodel.2006.02.037), lacking both detailed process representation and empirical underpinning. Whereas the latter has been addressed in recent work, notably of [colleagues at the ETH](http://www.fe.ethz.ch/research/standdynamics/index), the process-based design of [iLand](../wiki/iland.qmd) enables us to strive for a simple yet process-oriented representation of tree death. We’re currently looking into using a trees’ carbon balance, i.e. how well a tree is able to sustain its living tissue, as an indicator of its stress and predisposition to mortality. In other words, if the “spending” of a tree for supporting vital organs such as leaves and roots exceeds its gains from photosynthesis, it has to draw on its reserves and gets increasingly prone to pressures (e.g., pathogens), eventually succumbing to them. In [iLand](../wiki/iland.qmd), such a C balance indicator is a process-oriented proxy of a trees’ environmental influences, its competitive status and life history- and thus a good integrating indicator for mortality. Yet, accounting for the limited experiences with such approaches, we’re currently looking into a [probabilistic design](http://dx.doi.org/10.1016/S0304-3800(00) model design, in response to the still limited understanding of the variability in observed mortality patterns. We’re quite eager to test such assumptions against both hypotheses and data, as mortality eventually frees resources for regeneration, thus being essential in the cycle of forest dynamics.
