---
title: "Gauging forest carbon with iLand"
date: "2012-08-31"
author: "Rupert Seidl"
---

For those of you who didn’t catch the [iLand presentation at ESA](blogpost37-iland-esa.qmd), here’s a short summary of what is the first fully-fledged landscape scale application of iLand (you can read more about it in a recently accepted paper in [Ecosystems](https://dx.doi.org/10.1007/s10021-012-9587-2)). The background and motivation to the study was that forest ecosystems [store large amounts of carbon (C)](http://dx.doi.org/10.1126/science.1201609), and take up C from the atmosphere, mitigating the anthropogenic greenhouse effect. The amount of C stored in forests, however, [varies considerably in the landscape](http://www.whrc.org/mapping/nbcd/index.html), and our understanding of what causes this variation is still limited.

We used [iLand](../index.qmd) to unravel the main drivers of forest C stocks at the [HJ Andrews Experimental Forest (HJA)](http://andrewsforest.oregonstate.edu/) in Oregon. A key methodological issues that iLand helped to resolve was that a multitude of - hierarchically nested - drivers affect the processes in forest ecosystems, making it anything else but straight forward to interpret correlations of individual factors with forest C stocks. Climate, for example, influences carbon-relevant process rates like heterotrophic respiration (i.e., the flux of C from the soil back to the atmosphere) directly, but also affects the species composition of a forest (which in turn can affect the C cycle). The reason why we in particular tried to understand the role of climate on forest C is that [climate will likely change drastically in the future](http://www.ipcc.ch/), making it important to understand how sensitive forest C stocks are to such changes. On the other hand, aspects like species composition and stand structure are the factors that we can influence directly by [means of forest management](http://www.wabo.boku.ac.at/wb-fachgebiete.html?&amp;L=1). Managing forests for climate change mitigation thus requires an understanding of what features can positively influence the forest C balance, and to what degree.

Using iLand, we disentangled drivers of forest C storage at the HJA, with quite interesting results. Contrary to other study we found that variation climate only accounted for approximately half of the variation in C, despite the fact that our study landscape is characterized by strong environmental gradients and complex terrain. The effects of forest structure and composition were found to be in the same order of magnitude than that of environmental drivers. In particular, we found that diversity in species and structure was positively associated with higher C stocks. In other words, old-growth features like diversity in tree species and sizes are not only important for species depending on forests for habitat, but they also enhance forest C stocks – adding one more reason to [managing for complexity](http://books.google.fr/books?id=NJwN3b1csDoC&amp;lpg=PP1&amp;hl=de&amp;pg=PP1#v=onepage&amp;q&amp;f=false)! Read more and download the full article [here](https://dx.doi.org/10.1007/s10021-012-9587-2).
