---
title: "On scaling (part 1)"
date: "2013-10-08"
author: "Rupert Seidl"
---

I wanted to share some more thoughts on scales and scaling in ecosystem management (and subsequently in modeling) for quite a while now, and will take the recent publication of [a paper on the issue](http://dx.doi.org/10.1007/s10342-013-0725-y) as an opportunity to finally do so. This'll be a two-part post with some more general thoughts in pt.1 and a practical example of scale effects in pt.2.

Before I start, I however also want to make clear that I do not attempt to provide an exhaustive summary on the vast [literature on scaling in ecology](http://onlinelibrary.wiley.com/doi/10.1111/ele.12048/abstract) here. Scaling is one of the central problems in ecology, and others have elaborated more deeply and clearly on it that I ever could (see e.g., the seminal papers [here](http://www.esajournals.org/doi/abs/10.2307/1941447) and [here](http://www.jstor.org/discover/10.2307/2389612?uid=3737528&amp;uid=2129&amp;uid=2&amp;uid=70&amp;uid=4&amp;sid=21102747619243‎)).

What I find interesting though, coming at it from an applied angle, is that scaling issues are for the most part not explicitly addressed in the applied disciplines, such as in forestry. Of course, many traditional concepts of forestry are inherently scale-dependent. Think sustainable yield, which is not achieved at the entity of actual management decision making (the stand scale) but at the hierarchically higher management unit level (the landscape scale). So while the importance of different scales is generally acknowledged in forestry, scaling up is oftentimes perceived as not much more than adding up trees. This naïve view of scaling, however, neglects that some processes change nonlinearly with scale, that others are relevant and can only be described at particular scales, and that interactions across scales can have strong impacts on ecosystem dynamics (if you care for the technical terms, check out transmutation, emergence, and path dependence for starters). Yet, I would argue that many of these issues are crucial in the context of current challenges of forest management, from managing to conserve biodiversity to mitigating climate change in forestry. This, imho, asks for a stronger consideration of scaling issues in management.

We’ve described some examples for scaling issues in forest management in more detail in the [paper](http://dx.doi.org/10.1007/s10342-013-0725-y) – here I want to come back to modeling though. The modelers amongst you will probably agree that design decisions about spatial and temporal scale are among the most important in developing a model. They ultimately determine which processes can be accommodated within the framework of a model, and which questions can be addressed with it (e.g., dispersal and migration cannot be modeled at the stand scale in any meaningful way). In many instances, different scales increase the complexity of the problem. Generally speaking, this is counter to the art of modeling, which is to reduce the real life complexity to (mathematically) tractable levels. On the other hand, scaling can be a modeler’s best friend, as often predictability of ecological processes [increases with scale](http://www.jstor.org/discover/10.2307/2389612?uid=3737528&amp;uid=2129&amp;uid=2&amp;uid=70&amp;uid=4&amp;sid=21102747619243). So choosing scales wisely can make a great difference in modeling. The traditional way of doing it was to carefully select a focal scale to match the questions and processes to be addressed with a model. This usually leaves processes at underlying scales implicitly lumped into gross equations, while controlling for processes at higher hierarchical levels by assuming them constant (or random). This reductionist approach makes for very successful and powerful models at their particular scales. Yet, it foregoes one imho increasingly important application of models, and that is to understand and predict cross-scale phenomena. Ultimately, if you’re interested in an emergent property such as resilience, for instance, you need to capture exactly this emergence in order to be able to simulate and predict it. If, because focused on a single scale, you inhibit emergence in the model by design, your model will not do a good job in addressing such a property.

My main point here is that many of the current challenges in forest management are multi-scale issues. And in order to address these multi-scale issues we need multi-scale models, as only those will help us understand these complex properties better, and ultimately help managers to resolve their scaling-related management issues. Scaling is, after all, one of the [major strengths of simulation models](http://dx.doi.org/10.1007/s00267-009-9414-5) in the context of ecosystem management. Just to show you that this multi-scale modeling is more than just an intellectual exercise and can actually be done in practice, have a look [here](../wiki/scaling.qmd). Also, I promise that [part 2 of the scaling post](blogpost48-on-scaling-part-2.qmd) will be less theoretical and more hands-on, so stay tuned!
