---
title: "On scaling (part 2)"
date: "2013-11-17"
author: "Rupert Seidl"
---

After the theoretically motivated [post about scaling](blogpost46-on-scaling-part-1.qmd) not too long ago I thought that it’d be insightful to illustrate the role of scale with an example. [We recently did some work](http://www.austroclim.at/index.php?id=startclim2011) aiming to get a better understanding what drives the spatio-temporal differences in the disturbance regimes auf Austria (more info in the paper [here](http://dx.doi.org/10.1016/j.foreco.2013.07.017)). For this we had a nice dataset available courtesy of our colleages over at [BFW](http://bfw.ac.at/rz/bfwcms.web?dok=34), covering the full 3.99 Mill. ha of Austria’s forests for the period of 2002-2010. As we started wading through the exceedingly long list of potential explanatory variables for which we hypothesized an influence on disturbance regimes we quickly realized that we’d need to structure our analysis along some overarching theory/ hypothesis in order to make (ecological) sense of all the possible statistical relationships in such a dataset.

After some thinking we turned to a quite seasoned [theory of tree death](http://books.google.at/books?id=4ShIAAAAYAAJ) first put forward by Paul Manion in the 1980s. In his theory Manion suggests that slow “background” factors predispose a tree to be affected by disturbance and death, while fast, inciting factors are what trigger the actual occurrence of such an event. This distinction along the lines of different temporal scales has more recently also been proposed as an important [approach to understand complex systems](http://dx.doi.org/10.1007/s100210000043). Applying this approach sequentially in our study of the Austrian disturbance regime (i.e., first controlling for slowly changing spatial differences in predisposition (e.g., tree species composition), and subsequently investigating the effect of inciting factors such as the inter-annual changes in weather patterns) [showed that both variable groups explained a significant portion of the spatio-temporal variance in disturbance](http://dx.doi.org/10.1016/j.foreco.2013.07.017). In other words, when we include variables at different (temporal) scales we increase our inferential power, and learn more about the system than if we were to focus solely on a single temporal scale.

What’s more is that the analysis at different scales also revealed quite interesting (and at first glance counter-intuitive) results with regard to ecological processes: As expected, we found the occurrence of gale-force gusts (fast variable) to be positively related to damage by wind disturbance. However, when considering windiness over longer periods of time (mean windiness, i.e. a slow variable of average wind exposure), we found that the sign changed, and – all else being equal – trees in windy regions accrued less damage from wind disturbance. This indicates a significant acclimation effect of forests through structural adaptation of the tree’s anchorage to wind loading. It also shows that evaluating risk (and changes therein) by simply extrapolating observations made at short time scales might lead to errors by neglecting the feedbacks and adaptive capacity of ecosystems. Thus, for addressing such questions I say: consider [going multiscale](http://dx.doi.org/10.1007/s10342-013-0725-y)!
