---
title: "a disturbed future?"
date: "2010-12-06"
author: "Rupert Seidl"
---

First of all, apologies for the long intervals between posts. The fact that I haven’t been posting any news for quite a while doesn’t mean that there is no progress in our project though. In fact quite the opposite is true, one could say that the “iLand jigsaw” has been [falling into place](http://www.youtube.com/watch?v=GoLJJRIWCLU&NR=1) over the last month and that we’re already discussing first potential applications of the model. What I want to write about today thus focuses less on the latest achievements in model development (I promise to write another post on that soon), but rather on why this is all useful and what we can potentially gain from it.

I recently had the opportunity to work with a group of colleagues from a variety of countries and background on the current state of the art in [modeling natural disturbances in forest ecosystems](http://dx.doi.org/10.1016/j.ecolmodel.2010.09.040). Looking at a number of different disturbance agents, from wildfire to ungulate browsing, while applying an unifying analysis framework from disturbance ecology gave us a unique perspective on the advances and challenges in disturbance modeling. One thing that we found was that disturbance modeling really took off over the last 15 years, with a steep increase in the number of models and approaches published. This is good news, considering that a [recent analysis](http://dx.doi.org/10.1890/10-0097.1) by one of the doyens of the field, [Monica Turner](http://landscape.zoology.wisc.edu/People/Turner.html), underlines that disturbances are of crucial importance in ecology, and need to receive more attention in the future, particularly taking into account the potential effects of climate change on disturbance processes. She states that “*spatial and temporal variation in disturbance and successional processes must be incorporated more explicitly into studies of global change*”, and that “*ecologists must increase efforts to understand and anticipate the causes and consequences of changing disturbance regimes*”. Modeling is a prime tool for addressing these challenges. However, what [our disturbance modeling analysis](http://dx.doi.org/10.1016/j.ecolmodel.2010.09.040) also documented, was that although the number and application of disturbance models increases, the integrated, process-based, and dynamic systems approach necessary to fully address the issues that we’re facing still remains challenging.

This challenge is one major motivation for developing [iLand](../wiki/iland.qmd): Operating from a hierarchical multi-scale perspective, and scaling explicitly from the individual tree to the landscape makes iLand a suitable platform to incorporate disturbance processes that are driven by local conditions, but have the potential to effect large forest landscapes. These complex interactions between vegetation and disturbance agents, both mediated by climate, can be explicitly simulated in iLand, and allow us to investigate altered disturbance regimes and novel trajectories as emerging property of the model. We’re excited about using our approach in this context, and contribute to an improved understanding of potential climate change effects on forest ecosystems.
