---
title: "The fire season is (still) on!"
date: "2011-12-04"
author: "Rupert Seidl"
---

Time for another update from the iLand world. But before I dive into the details of the “hot” topic ***fire disturbance***: I’ve been recently checking the stats of the [iLand blogs](index.qmd), and together this blog and its [sister blog](index.qmd) have had close to 2000 visits as of today. Well, it’s not exactly the definition of “going viral”, but considering the rather specific topic I think that 2 visitors a day on average since the blogs are online is not too bad. So thanks everybody for your interest in our work!

But back to disturbance modeling, and fire in particular. As [Werner already reported](blogpost28-summer-time-is-fire-time.qmd) we’re thinking about wildfire for quite a while now, and actually came a long way in simulating it in iLand. Working in Oregon, and at the [HJ Andrews Experimental Forest](http://andrewsforest.oregonstate.edu/) in particular, fire disturbance is one of the ***crucial drivers of ecosystem dynamics***, and given the [disturbance focus](../wiki/project-abstract.qmd) in iLand was thus a logical inclusion in our model. In particular, the research on the fire regimes of the western US has taken quite an interesting turn recently, with a more differentiated view of fires gradually replacing the traditional high severity – low severity fire regime dichotomy. Experts are increasingly trying to understand what are now termed ***[mixed severity fire regimes](http://dx.doi.org/10.1016/j.foreco.2011.05.004)***, where a complex interplay of weather, topography, and vegetation creates a variable pattern of fire effects. And we think that iLand could make an interesting contribution to this discussion, as the high resolution (both spatially and with regard to explicitly simulated ecosystem processes) of the model could help to understand the complex interplay between drivers and effects of such mixed severity fire regimes.

Now for those of you in Central and Northern Europe fire might not be the first disturbance agent that comes to mind in thinking about temperate forests. Well, but with climate change [we might have to think again](http://dx.doi.org/10.1111/j.1365-2486.2011.02452.x). ***Fires are increasing*** also in places like Austria, and this year, for instance, a particularly dry fall made for an [extremely long fire season](http://derstandard.at/1319183201686/Anhaltende-Trockenheit-Erhoehte-Waldbrandgefahr-in-Tirol). As of this writing (beginning of December), there are [still fires going in the Alps](http://derstandard.at/1319183954350/Tirol-Waldbrand-im-Paznauntal-Noch-immer-Glutnester). So fire might also become more important in central Europe, and there are currently [several](https://forschung.boku.ac.at/fis/suchen.projekt_uebersicht?sprache_in=de&menue_id_in=300&id_in=7029) [research](https://forschung.boku.ac.at/fis/suchen.projekt_uebersicht?sprache_in=de&menue_id_in=300&id_in=7891) [projects](https://forschung.boku.ac.at/fis/suchen.projekt_uebersicht?sprache_in=de&menue_id_in=300&id_in=8657) on the way to better understand fire dynamics in these forests. We hope that we’ll be able to contribute a simulation perspective to these efforts with iLand in the near future, and in doing so maybe facilitate a ***knowledge transfer*** from a well-studied fire system (the Pacific Northwest) to a region where knowledge about fire ecology is still scarce (central Europe).

But for those of you who come here for the more ***technical aspects***, just briefly, how do we simulate fire in iLand? Well, our premise was (again) to start by asking what we wanted to use the model for, and then define the level of detail from there. The objectives that we defined for us read like this:

* to model ***fire regimes as an emerging property*** of vegetation and climate,
* to include processes of ***individual-tree fire resistance*** in order to simulate complex and heterogeneous fire impacts,
* to take into account ***landscape heterogeneity*** on fire processes, and
* to be ***sensitive to climate*** and thus applicable under climate change conditions.

In a nutshell, we’re using a [cellular automaton approach](http://en.wikipedia.org/wiki/Cellular_automaton) to simulate fire spread spatially explicit on 20m cells in the landscape. Ignitions are handled probability-based, and impacts are simulated at the level of individual trees (i.e. making use of the detailed structure provided by the iLand vegetation simulations), based on a simplified estimation of fire intensity. Basically our approach is a hybrid between the way fires are simulated in [FireBGC v2](http://www.firelab.org/research-projects/fire-ecology/139-firebgc) and [LandClim](http://www.fe.ethz.ch/research/disturbance/landclim) (I’ve been recently asked what the closest neighbor models of iLand would be if one would do an ordination of simulation models, and both FireBGC v2 and LandClim would be close contenders, see also [here](../wiki/iland-model-complexity-and-its-niche-in-the-landscape-of-models.qmd)). Currently, we’re testing the model at HJA, with quite interesting results… but that’s a story for another post. Stay tuned!
