---
title: "Learning from LANDIS-II"
date: "2009-09-03"
author: "Rupert Seidl"
---

One particular vision and objective with [iLand](../wiki/iland.qmd) is to integrate the ideas and concepts of [individual based, stand level forest modeling](http://dx.doi.org/10.1016/j.ppees.2007.11.002) with those of [landscape ecology and modeling](http://dx.doi.org/10.1007/s10980-006-9048-4). To facilitate that idea we are currently holding a workshop with the core [LANDIS-II](http://www.landis-ii.org/) developers [Rob Scheller](http://www.consbio.org/about/staff-board-1/Robert-M.-Scheller-Ph.D) and [Jimm Domingo](http://www.green-code.com/) in Corvallis. Discussing landscape issues (e.g., spatial interactions) both at the conceptual/ecological level as well as at the technical/implementation-oriented level gives us the unique opportunity to learn from the long experience of the LANDIS-II team and ensure compatibility with regard to certain aspects of the highly [modular LANDIS-II](http://dx.doi.org/10.1016/j.ecolmodel.2006.10.009) structure, e.g. to design interfaces for compatibility with LANDIS-II extensions. Their newly extracted spatial library (available [here](http://code.google.com/p/landis-ii/)), but also their approaches to model spatio-temporal dynamics of seed dispersal, forest management and disturbances in particular are highly relevant for our work in iLand. Rather than re-inventing the wheel wrt these processes the cooperation with the LANDIS-II team allows us to tap into their knowhow, bringing us a step closer to actually bridging the gap between [individual based ecology](http://books.google.com/books?id=12MvUbMeog8C&lpg=PP1&dq=grimm) and [landscape ecology](http://books.google.com/books?id=UiOXwoMNuKkC&lpg=PA3&dq=landscape). And besides, working with them is really inspiring and fun…