---
title: "Why trees grow (and how…)"
date: "2009-09-25"
author: "Rupert Seidl"
---

How trees capture radiation energy, how efficient they are in converting it to carbon, what environmental factors (and interactions among factors) are influencing this process, for which organs (e.g., leaves, roots, stem) the produced biomass is used… these are just some of the questions addressed by [tree physiology](http://treephys.oxfordjournals.org/). Rather than approximating the process of tree growth statistically relying on models based on physiological principles is important particularly since such models are more robust in predicting the effects of [climatic change](http://www.ipcc.ch/) on ecosystem processes.
A large variety of models based in physiology exist, the challenge in [iLand](../wiki/iland.qmd) is, to incorporate physiological knowledge on growth processes in a balanced way with other ecosystem processes (e.g., mortality, regeneration), addressing the level of individual trees but keeping it scalable to watershed and landscape scale. Currently, the idea is to use a [radiation use efficiency](http://dx.doi.org/10.1071/FP02088) approach in [iLand](../wiki/iland.qmd), which calculates the canopy carbon gain based on intercepted radiation and an efficiency measure of converting this radiation into primary production, taking constraints by environmental factors explicitly into account. The seminal paper of [Landsberg and Waring (1997)](http://dx.doi.org/10.1016/S0378-1127(97), for instance, presents such a model, and their approach has also proven to be suitable in an ecosystem dynamics context (i.e., [hybridizing physiological and successional concepts of forest modeling](http://treephys.oxfordjournals.org/cgi/reprint/25/7/939)). I had the opportunity to discuss prospects and details of such an approach recently with [Dick Waring](http://www.forestry.oregonstate.edu/cof/fs/people/faculty/waring.php) here at OSU, and it seems that one more piece of the (iLand) puzzle slowly falls into place… I’m trying not to get too excited yet (as model building is an iterative process and we’re still in the first iteration loop), but we’re expecting the first trees to grow in our virtual environment in the near future!
