---
title: "the end is the beginning…"
date: "2012-05-17"
author: "Rupert Seidl"
---

It’s a few weeks now since the project funding the initial development of iLand, an [European Commission FP7 Marie Curie International Outgoing Fellowship (IOF)](http://ec.europa.eu/research/mariecurieactions/), came to a close. Time to reflect some more on the past and future of iLand…

Looking back, the IOF was a great opportunity to develop a new simulation tool, particularly considering that grant programs funding the development of new methodologies are becoming fewer in favor of research directly addressing the [“grand challenges”](http://ec.europa.eu/research/horizon2020/index_en.cfm?pg=europe-2020) of today (I would argue that we direly need the former to do the latter, but that’s just my two cents, for what they are worth). Also, three years was a great time frame for such an endeavor, with enough time to really dive into the topic, study the literature extensively, and [play around with approaches developed previously](../wiki/iland-model-complexity-and-its-niche-in-the-landscape-of-models.qmd) before sitting down and starting to sketch out new ideas (the [iLand history pages](../wiki/history.qmd) give a little glimpse into the past of the model).

I just once more read through the [project proposal](../wiki/project-abstract.qmd) and the reviews thereof, contrasting what we had proposed four years ago with what we have accomplished. To put it with the words of a Reviewer of the proposal: “*The plan is ambitious*”. It certainly was, and it certainly took a lot of energy to get where we are now. But, as [E.H. Land](http://en.wikipedia.org/wiki/Edwin_H._Land) said: "*Don't undertake a project unless it's manifestly important and nearly impossible.*” Considering that we have accomplished all the main objectives of the project is thus all the more satisfying – a big thank you to everybody who contributed to making this success possible.

Which brings me to the future of iLand: The end of the initial IOF is of course not the end of the model, it on the contrary marks a new phase in the “life” of iLand. After three years of basic model development we’re eager to see iLand being put to use. With the first [#applications|application paper](../wiki/iland-publications.qmd) already in review, and iLand being a central part of several proposals currently being evaluated we’re confident to see the model addressing current questions of ecosystem dynamics and management soon. To highlight just one activity: iLand is currently used to assess biodiversity – ecosystem functioning relationships across forested landscapes within the frame of the [EC FP7 collaborative project FunDivEUROPE](http://www.fundiveurope.eu/).

But of course we also have plenty of ideas on how to further improve the model, including (but not limited to) adding to the range of disturbance agents (currently modules for wildfire and wind are operational, with a bark beetle module being in the planning stage) and thinking about spatially explicit competition for resources other than light. To conclude this post with another quote of the proposal review: “*This project should be considered as a first step in the development of a new analysis/ modeling tool; […] this fellowship is the beginning of a longer-term effort in forest ecosystem model development*”. I couldn’t have said it better myself - the “[fellowship of iLand](http://www.youtube.com/watch?v=o8ohAwSdIw8)” is well on its way to new quests (and we’d be more than happy to hear from you if you’d want to join us on this journey, or have ideas with regard to its direction).

