## Example for DBH-Distribution barcharts

library(RSQLite)
library(ggplot2)
library(plyr)
library(reshape)  
library(scales)

cols.species <- c("abal"="#2F1BE0",
                  "lade"="#1BD3E0",
                  "pisy"="#F7430C",
                  "fasy"="#1BE06D",
                  "quro"="#E08E1B",
                  "acps"="#E01BD9",
                  "frex"="#871BE0",
                  "cabe"="#1B32E0",
                  "bepe"="#1B91E0",
                  "alin"="#1BE0AF",
                  "qupe"="#22E01B",
                  "psme"="#D6F288",
                  "algl"="#F2D288",
                  "casa"="#F29488",
                  "pini"="#F288A6",
                  "acca"="#DB88F2",
                  "acpl"="#9988F2",
                  "qupu"="#88C6F2",
                  "pice"="#88F2D4",
                  "soau"="#86E38C",
                  "soar"="#E3D586",
                  "coav"="#E3BB86",
                  "alvi"="#E39C86",
                  "potr"="#02B4FA",
                  "poni"="#8C70B5",
                  "tico"="#02E9FA",
                  "tipl"="#02FA6E",
                  "ulgl"="#82FA02",
                  "saca"="#FAFA02",
                  "rops"="#FA8602")

### custom function for creating the dbh-distribution charts
### the data is generated by the "Dynamic stand" output of iLand.
barchart_graphs <-function(data, label) {
  ## extract dbh classes
  count_ha.sp=data.frame(species=data$species, dbh10=data$if_dbh_10_1_0_sum/100, dbh20=data$if_dbh_10_and_dbh_20_1_0_sum/100, dbh30=data$if_dbh_20_and_dbh_30_1_0_sum/100, dbh40=data$if_dbh_30_and_dbh_40_1_0_sum/100, dbh50=data$if_dbh_40_and_dbh_50_1_0_sum/100, dbh60=data$if_dbh_50_and_dbh_60_1_0_sum/100, dbh70=data$if_dbh_60_and_dbh_70_1_0_sum/100, dbh80=data$if_dbh_70_and_dbh_80_1_0_sum/100, dbh90=data$if_dbh_80_and_dbh_90_1_0_sum/100, dbh100=data$if_dbh_90_and_dbh_100_1_0_sum/100, dbh100plus=data$if_dbh_100_1_0_sum/100)
  # reshape (melt)
  count_ha.sp.melted <- melt.data.frame(count_ha.sp, id.vars="species", na.rm=FALSE)
  # and calculate a total
  count_ha.total <- colSums(count_ha.sp[,2:12])
  # now the plotting:
  barplot(count_ha.total+1, log="y", main=paste("Stemnumbers", label), ylab="N (+1)")
  ## the ggplot
  ggplot(count_ha.sp.melted, aes(x=variable,y=value,group=variable,fill=species)) + 
    geom_bar(stat="identity")  + scale_fill_manual(values=cols.species)+ 
    labs(xlab="dbh classes", ylab="Stem number", title=paste("dbh distribution", label))
}

#### load data from the database ######
conn<-dbConnect("SQLite", dbname = "e:/Daten/iLand/projects/Hainich/output/Hain_pnv.sqlite")
dyn.out=dbReadTable(conn,"dynamicstand")
dbDisconnect(conn)

summary(dyn.out)



### create charts for several timesteps ########
#data <- dyn.out[dyn.out$year == 50,]
par(mfrow=c(1,1))
pdf(file="e:/Daten/iLand/projects/Hainich/tests/test_wr/run_bugfix_v2.pdf")
barchart_graphs(dyn.out[dyn.out$year == 50,], "50")
barchart_graphs(dyn.out[dyn.out$year == 100,], "100")
barchart_graphs(dyn.out[dyn.out$year == 250,], "250")
barchart_graphs(dyn.out[dyn.out$year == 500,], "500")
barchart_graphs(dyn.out[dyn.out$year == 600,], "600")

dev.off()

