name: Qt qmake Cross-Platform Build

on:
  # 1. Trigger bei Erstellung eines Releases
  release:
    types: [published]

  # 2. Manueller Trigger über das GitHub-Interface
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Grund für den manuellen Build (z.B. Dev-Test)'
        required: false
        default: 'Manual Dev Build'

  # 3. Optional: Trigger bei spezifischen Tags (z.B. v1.0, v2.1)
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.0'

      # Abhängigkeiten für FreeImage installieren
      - name: Install FreeImage (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfreeimage-dev

      - name: Install FreeImage (macOS)
        if: runner.os == 'macOS'
        run: brew install freeimage

      - name: Build Project
        shell: bash
        run: |
          # run build script
          ./build_iland.sh
          cd build
          qmake ../YourProject.pro
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            nmake # Oder 'jom' falls konfiguriert
          else
            make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)
          fi


      - name: Windows Deployment
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # create a directory for release
          mkdir deploy-win
          # copy all executables and FreeImage.dll
          copy src/iland/build/release/release/iland.exe deploy-win
          copy src/ilandc/build/release/release/ilandc.exe deploy-win
          copy src/fonstudio/build/release/release/fonstudio.exe deploy-win
          copy libs/win/FreeImage.dll deploy-win

          # 2. run windeployqt to collect
          windeployqt --release --no-translations --compiler-runtime --qmldir src\iland\qml deploy-win/iland.exe

      - name: Upload Windows Build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build-Ready-To-Run
          path: deploy-win/



      - name: Upload Windows Build & Logs
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
            name: iLand-Windows-Build-and-Logs
            path: |
                deploy-win/build_log.txt
